### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by LemurXD** [DrManganese/TOPAddons#103]
**Describe the bug** 
The Bug is a glitch where if you look and shift at a pressurized tube with a configurator your game will crash.

**Expected behavior**
I expected the tube to disconnect from another tube.

Version: All the mods 6 version 1.6.4 from curse forge.

[2021-05-22-6.log](https://github.com/DrManganese/TOPAddons/files/6527267/2021-05-22-6.log)
[crash-2021-05-22_15.37.51-client.txt](https://github.com/DrManganese/TOPAddons/files/6527269/crash-2021-05-22_15.37.51-client.txt)

https://user-images.githubusercontent.com/84646199/119242587-47063680-bb1c-11eb-8a2c-b227b8c04ddb.mp4

**Comment by DrManganese** [comment]
Thanks for the report. Normally TOP Addons shouldn't add any Fluid information to the tubes since Mekanism is explicitly blacklisted.

Could it be that the server you are playing on has removed/disabled some mods that are still on the client? There is a known issue with The One Probe where the client and the server's custom "elements" are mismatched.

To test this: Could you try shift looking at a pressurized tube in single player and see if the same crash happens?

**Comment by DrManganese** [comment]
Related to McJty/TheOneProbe#472.

**Comment by DrManganese** [comment]
Closing this. Issue is on The One Probe side.
