### ISSUE TITLE
New version of TheOneProbe cause some issues + other issues

### ISSUE THREAD

**Issue by mcdodge34** [DrManganese/TOPAddons#8]
I've noticed some problems with your awesome TOP addon, like with the new version (just released today) of the The One Probe 1.2.0, by default we should see the content of Storage drawers, but if your mod is installed, we still have to sneak to see it no matter what we set in theoneprobe.cfg. Also noticed problems with Tinkers Construct Smeltery, it was a problem even before that new TheOneProbe version, if there's more than 1 liquid in the smeltery, it does show the liquids all at the same line which makes it impossible to read what liquids is in the smeltery exactly.

**Comment by DrManganese** [comment]
Hi, I'm guessing the smeltery issue happens most with big smelteries containing small amounts of multiple liquids, I think I know a way to make that more readable so that will be done.

I don't know how to solve the the Storage Drawers thing easily.  McJty has set it up so that it always shows the contents' icons and only the names when sneaking. Whereas my implementation shows icons, names and amounts when sneaking. 
I could imitate TOP's way: show icons when it's config has it enabled, and then show the rest of the info when sneaking. Or maybe there is a more user-friendly way you could come up with? 😋 
At the moment you have to sneak with TOP Addons installed because I disable contents display on drawers.

Thanks for the feedback!

**Comment by mcdodge34** [comment]
On storage drawers, number of items is good to know at all time, but when sneaking knowing how much the drawer can hold and maybe which upgrade is installed would be nice, I think Waila or one of his addons did this if I remember correctly so maybe you could take a look at the code they used if the code is similar with The One Probe. For the Smeltery, its not only on small quantity of liquids, its like if every quantity was overlapping each others names, Here is a screenshot that defines what I mean : maybe having the name of the liquid not on the liquid itself could also help a little bit : http://imgur.com/a/cEsvW

**Comment by DrManganese** [comment]
Alright, so every liquid now has a minimum height so that their names fit, I couldn't think of any other way of displaying the names yet. https://i.imgur.com/l0DkJz4.png

And this is how storage drawers behave now (vanilla TOP behavior when not sneaking, TOP Addons behavior when sneaking). http://imgur.com/a/4VWpZ

**Comment by mcdodge34** [comment]
Alright, awesome job, on my next server update list, probably on friday, I always wait so if there's major bugs on the new version of mods I add, they are usually fixed before I put them on my server.
